// authInfo
const SET_AUTH_INFO = 'SET_AUTH_INFO';
const CLEAR_AUTH_INFO_STORE = 'CLEAR_AUTH_INFO_STORE';
// breadcrumb
const CHANGE_BREADCRUMB = 'CHANGE_BREADCRUMB';
const RESET_BREADCRUMB = 'SET_AUTH_INFO';
const CLEAR_BREADCRUMB_STORE = 'CLEAR_BREADCRUMB_STORE';

// collapsed
const CHANGE_COLLAPSED = 'CHANGE_COLLAPSED';
const CLEAR_COLLAPSED_STORE = 'CLEAR_COLLAPSED_STORE';

// openKeys
const SET_OPEN_KEYS = 'SET_OPEN_KEYS';
const CLEAR_OPEN_KEYS_STORE = 'CLEAR_OPEN_KEYS_STORE';

// selectKeys
const SET_SELECT_KEYS = 'SET_SELECT_KEYS';
const CLEAR_SELECT_KEYS_STORE = 'CLEAR_SELECT_KEYS_STORE';

export {
  // authInfo
  SET_AUTH_INFO,
  CLEAR_AUTH_INFO_STORE,
  // breadcrumb
  CHANGE_BREADCRUMB,
  RESET_BREADCRUMB,
  CLEAR_BREADCRUMB_STORE,
  //collapsed
  CHANGE_COLLAPSED,
  CLEAR_COLLAPSED_STORE,
  // openKeys
  SET_OPEN_KEYS,
  CLEAR_OPEN_KEYS_STORE,
  // selectKeys
  SET_SELECT_KEYS,
  //
  CLEAR_SELECT_KEYS_STORE
};
